[package]
name = "font-rs"
version = "0.1.3"
license = "Apache-2.0"
authors = [ "Raph Levien <raph@google.com>" ]
keywords = ["font", "truetype", "ttf"]
description = "A font renderer written (mostly) in pure, safe Rust"
repository = "https://github.com/google/font-rs"
build = "build.rs"

[dependencies]
math = { git = "https://github.com/roblabla/math.rs.git" }

[dependencies.hashbrown]
features = ["nightly"]
version = "0.1.8"

[features]
sse = []

[target.'cfg(target_feature = "sse")'.build-dependencies]
gcc = "0.3"
